Features/products
yana-shkvarovskaya/team11-project pull request #3
Opened 2021-09-09 10:20 UTC by ZhenyaHorlach

Добавляет верстку раздела + изображения в png

2021-09-09 11:08 UTC, yana-shkvarovskaya requested changes

2021-09-09 11:08 UTC, yana-shkvarovskaya commented on src/partials/products.html
> +                    <img srcset="
Попробовать реализовать эти img псевдоэлементами

2021-09-09 11:08 UTC, yana-shkvarovskaya commented on src/partials/products.html
> +                    <button type="button" class="products__button"></button>
Давай тут пропишем class="button products__button", чтоб к этим кнопкам потянулись общие стили для кнопок, которые создадим

2021-09-09 11:10 UTC, ZhenyaHorlach commented on src/partials/products.html
> +                    <img srcset="
Принято

2021-09-09 11:11 UTC, ZhenyaHorlach commented on src/partials/products.html
> +                    <button type="button" class="products__button"></button>
Принято

2021-09-09 11:23 UTC, ZhenyaHorlach commented on src/partials/products.html
> +                    <button type="button" class="products__button"></button>
Готово!

2021-09-09 13:09 UTC, yana-shkvarovskaya requested changes

2021-09-09 13:09 UTC, yana-shkvarovskaya commented on src/sass/_products.scss
> +.products__title-main {
Нужно изменить на общие стили из нормалайз

2021-09-09 13:09 UTC, yana-shkvarovskaya commented on src/sass/_products.scss
> +.products__title {
Нужно изменить на общие стили из нормалайз

2021-09-10 06:31 UTC, ZhenyaHorlach commented on src/sass/_products.scss
> +.products__title-main {
Готово!

2021-09-10 06:31 UTC, ZhenyaHorlach commented on src/sass/_products.scss
> +.products__title {
Готово!

2021-09-10 06:31 UTC, ZhenyaHorlach commented on src/partials/products.html
> +                    <img srcset="
Готово!

2021-09-10 15:27 UTC, yana-shkvarovskaya approved these changes

2021-09-10 15:27 UTC, merged