Featute/header
yana-shkvarovskaya/team11-project pull request #7
Opened 2021-09-09 17:04 UTC by Ann456

Добавлена разметка

2021-09-09 17:38 UTC, yana-shkvarovskaya requested changes

2021-09-09 17:38 UTC, yana-shkvarovskaya commented on src/images/symbol-defs.svg
> +<svg aria-hidden="true" style="position: absolute; width: 0; height: 0; overflow: hidden;" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
А ты не хочешь это в спринте сделать?

2021-09-09 17:38 UTC, yana-shkvarovskaya commented on src/partials/header.html
> +                                <li class="menu-nav__item"><a class="menu-nav__link" href="portfolio.html"
Вот и причина почему у тебя ошибка в разработчике

2021-09-09 17:38 UTC, yana-shkvarovskaya commented on src/partials/header.html
> +                                <li class="menu-nav__item"><a class="menu-nav__link" href="#" title="How it’s made?">How it’s made?</a></li>
Нужно учесть, что это должны будут быть якорные ссылки
Уже можно соответственно оформить эту часть, по желанию

2021-09-09 17:38 UTC, yana-shkvarovskaya commented on src/partials/header.html
> +                                    <li class="mobile-nav__item"><a class="mobile-nav__link" href="portfolio.html"
тут та же проблема с portfolio.html

2021-09-09 19:38 UTC, Ann456 commented on src/images/symbol-defs.svg
> +<svg aria-hidden="true" style="position: absolute; width: 0; height: 0; overflow: hidden;" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
Да, сделаю

2021-09-09 19:38 UTC, Ann456 commented on src/partials/header.html
> +                                <li class="menu-nav__item"><a class="menu-nav__link" href="portfolio.html"
Помогло частично!)

2021-09-09 19:39 UTC, Ann456 commented on src/partials/header.html
> +                                <li class="menu-nav__item"><a class="menu-nav__link" href="#" title="How it’s made?">How it’s made?</a></li>
ок

2021-09-09 19:39 UTC, Ann456 commented on src/partials/header.html
> +                                    <li class="mobile-nav__item"><a class="mobile-nav__link" href="portfolio.html"
исправлю

2021-09-10 05:22 UTC, yana-shkvarovskaya requested changes

2021-09-10 05:22 UTC, yana-shkvarovskaya commented on src/sass/_header.scss
> +  background-color: #ffb8ca;
Для всех своих таких цветов и шрифтов использовать наши _variables

2021-09-10 05:22 UTC, yana-shkvarovskaya commented on src/partials/header.html
> +                                <li class="menu-nav__item"><a class="menu-nav__link" href="portfolio.html"
Только я нигде не вижу исправлений

2021-09-13 19:35 UTC, closed without merging